export const requiredByProvider: Record<string, string[]> = {
  PUSHOVER_ENABLED: ["PUSHOVER_USER_KEY", "PUSHOVER_APP_KEY"],
  GOTIFY_ENABLED: ["GOTIFY_DOMAIN", "GOTIFY_APP_TOKEN"],
  DISCORD_ENABLED: ["DISCORD_WEBHOOK_URL"],
  TELEGRAM_ENABLED: ["TELEGRAM_CHAT_ID", "TELEGRAM_BOT_TOKEN"],
  IFTTT_ENABLED: ["IFTTT_EVENT_NAME", "IFTTT_KEY"],
  SLACK_ENABLED: ["SLACK_WEBHOOK_URL"],
  SIGNAL_ENABLED: ["SIGNAL_URL", "SIGNAL_FROM_NUM", "SIGNAL_TO_NUM"],
  MATRIX_ENABLED: ["MATRIX_SERVER_URL", "MATRIX_USERNAME", "MATRIX_PASSWORD", "MATRIX_ROOM"],
  SNS_ENABLED: ["AWS_REGION", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SNS_TOPIC_ARN"],
  WEBHOOK_ENABLED: ["WEBHOOK_URL"],
  NTFY_ENABLED: ["NTFY_URL"],
}

export const notificationFieldNames = new Set([
  "NOTIFICATION_TITLE", "MOBILE_PUSH_ENABLED",
  ...Object.keys(requiredByProvider), ...Object.values(requiredByProvider).flat(),
  "GOTIFY_PRIORITY", "NTFY_TOKEN", "NTFY_PRIORITY",
])
